#!/bin/sh

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_HOME=$( cd "$( dirname "$0" )" && pwd )

APP_NAME=$(basename "$0")
APP_BASE_NAME=${APP_NAME%-*}

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD=java
fi

if ! command -v "$JAVACMD" >/dev/null 2>&1; then
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    exit 1
fi

DEFAULT_JVM_OPTS="${DEFAULT_JVM_OPTS} --add-opens=java.base/java.util=ALL-UNNAMED"
DEFAULT_JVM_OPTS="${DEFAULT_JVM_OPTS} --add-opens=java.base/java.lang.reflect=ALL-UNNAMED"
DEFAULT_JVM_OPTS="${DEFAULT_JVM_OPTS} --add-opens=java.base.text=ALL-UNNAMED"
DEFAULT_JVM_OPTS="${DEFAULT_JVM_OPTS} --add-opens=java.base.util=ALL-UNNAMED"

set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

exec "$JAVACMD" "$@"
